[package]
name = "ImageManager"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
epaint = "0.28.1"
image = { version = "0.25.2", features = ["webp", "tiff"] }
rfd = "0.15.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
